load("@gazelle_rs//test_support:test_rules.bzl", "aggregate_rust_test")
load("@rules_rs//rs:rust_library.bzl", "rust_library")

rust_library(
    name = "api",
    srcs = ["src/lib.rs"],
    crate_name = "api",
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["//visibility:public"],
)

aggregate_rust_test(
    name = "api_test",
    crate = ":api",
)
