caches:
  - name: bazel
    cache_key:
      - gazelle-rs-bazel-v1
      - agent: pipeline
      - agent: os
      - agent: arch
      - env: USE_BAZEL_VERSION
      - agent: step
        fallback_limit: true
      - env: BUILDKITE_COMMIT
    target_paths:
      - /tmp/gazelle-rs-ci/bin
      - /tmp/gazelle-rs-ci/bazelisk
      - /tmp/gazelle-rs-ci/repository
      - /tmp/gazelle-rs-ci/disk
