load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "report_engine",
    srcs = ["src/lib.rs"],
    crate_name = "report_engine",
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "//model:line_items",
        "@metadata_example_crates//:anyhow",
    ],
)

rust_test(
    name = "report_engine_test",
    crate = ":report_engine",
)
