# gazelle:map_kind rust_test aggregate_rust_test @gazelle_rs//test_support:test_rules.bzl

load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")

gazelle_binary(
    name = "gazelle_bin",
    languages = ["@gazelle_rs//rs"],
)

gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
)

# gazelle:rust_crate_catalog crates.json
