load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "service",
    srcs = ["src/lib.rs"],
    crate_name = "service",
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "//model",
        "@mixed_example_crates//:anyhow",
    ],
)

rust_test(
    name = "service_test",
    crate = ":service",
)
