load("@gazelle_rs//test_support:test_rules.bzl", "aggregate_rust_test")
load("@rules_rs//rs:rust_library.bzl", "rust_library")

rust_library(
    name = "unit",
    srcs = ["lib.rs"],
    crate_name = "unit",
    crate_root = "lib.rs",
    edition = "2021",
)

aggregate_rust_test(
    name = "unit_test",
    srcs = [
        "first.test.rs",
        "lib.rs",
        "second.test.rs",
    ],
    crate_name = "unit",
    crate_root = "lib.rs",
    edition = "2021",
    deps = ["//api"],
)
